/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PikminRouteImport } from './routes/pikmin'
import { Route as PataponRouteImport } from './routes/patapon'
import { Route as KirbyRouteImport } from './routes/kirby'
import { Route as IndexRouteImport } from './routes/index'

const PikminRoute = PikminRouteImport.update({
  id: '/pikmin',
  path: '/pikmin',
  getParentRoute: () => rootRouteImport,
} as any)
const PataponRoute = PataponRouteImport.update({
  id: '/patapon',
  path: '/patapon',
  getParentRoute: () => rootRouteImport,
} as any)
const KirbyRoute = KirbyRouteImport.update({
  id: '/kirby',
  path: '/kirby',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kirby': typeof KirbyRoute
  '/patapon': typeof PataponRoute
  '/pikmin': typeof PikminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kirby': typeof KirbyRoute
  '/patapon': typeof PataponRoute
  '/pikmin': typeof PikminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kirby': typeof KirbyRoute
  '/patapon': typeof PataponRoute
  '/pikmin': typeof PikminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kirby' | '/patapon' | '/pikmin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kirby' | '/patapon' | '/pikmin'
  id: '__root__' | '/' | '/kirby' | '/patapon' | '/pikmin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KirbyRoute: typeof KirbyRoute
  PataponRoute: typeof PataponRoute
  PikminRoute: typeof PikminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pikmin': {
      id: '/pikmin'
      path: '/pikmin'
      fullPath: '/pikmin'
      preLoaderRoute: typeof PikminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patapon': {
      id: '/patapon'
      path: '/patapon'
      fullPath: '/patapon'
      preLoaderRoute: typeof PataponRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kirby': {
      id: '/kirby'
      path: '/kirby'
      fullPath: '/kirby'
      preLoaderRoute: typeof KirbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KirbyRoute: KirbyRoute,
  PataponRoute: PataponRoute,
  PikminRoute: PikminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
